spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  flyway:
    enabled: true
    locations: classpath:db/migration
  main:
    banner-mode: off
  spring:
    security:
      debug: true
  logging:
    level:
      org.springframework.security: TRACE
      org.springframework.web: TRACE

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: localhost
    port: 6379
server:
  port: 8080

encryption:
  password: "your-secret-password"
  salt: "your-16-byte-hex-salt"
